[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "taxi addict sponsor park modify roast creek range neutral juice pattern ocean target leopard trick float start open icon across layer series assume remember"
